import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import Navbar from "./components/NavBar";
import { ThemeProvider } from "./components/theme-provider";

export const metadata: Metadata = {
  title: "The Skyline Production",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable} ${GeistMono.variable}`}
      suppressHydrationWarning
    >
      <body className="antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange={false} // Enable transitions
          storageKey="skyline-theme" // Custom storage key
        >
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
